---

- name: Remove default bind sample file 'pdns.simplebind.conf'
  file:
    name: "{{ pdns_config_dir }}/pdns.d/pdns.simplebind.conf"
    state: absent

- name: Ensure that the PowerDNS Authoritative Server configuration directory exists
  file:
    name: "{{ pdns_config_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0750

- name: Generate the PowerDNS Authoritative Server configuration
  template:
    src: pdns.conf.j2
    dest: "{{ pdns_config_dir }}/pdns.d/{{ pdns_config_file }}"
    owner: "root"
    group: "root"
    mode: 0640
  notify: Restart PowerDNS
