---

- name: Restart PowerDNS
  service:
    name: "{{ pdns_service_name }}"
    state: restarted

- name: reload systemd and restart PowerDNS
  command: systemctl daemon-reload
  notify: Restart PowerDNS
